services:
  log-generator:
    build: .
    container_name: logdrain-generator
    volumes:
      - log-data:/app/logs
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    ports:
      - '3100:3100'
    volumes:
      - ./config/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.9.0
    ports:
      - '9080:9080'
    volumes:
      - './config/promtail-config.yml:/etc/promtail/promtail-config.yml'
      - log-data:/app/logs
    depends_on:
      - loki
    command: -config.file=/etc/promtail/promtail-config.yml
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yml
      - ./config/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
      - ./dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki

volumes:
  log-data:
  grafana-data:
  loki-data:
